import { createContext, useContext, useState, useCallback, type ReactNode } from 'react';

export type LanguageCode = 'es' | 'en-US' | 'en-GB' | 'zh' | 'vi' | 'ar';

interface Translations {
  // Bottom bar
  ordersInQueue: string;
  sort: string;
  sortByTime: string;
  sortByTable: string;
  sortByType: string;
  grid: string;
  horizontal: string;
  stagger: string;

  // Sidebar
  menu: string;
  home: string;
  history: string;
  alerts: string;
  settings: string;
  newOrders: string;
  inProgress: string;
  hideCompleted: string;
  switchToPOS: string;

  // Order card
  products: string;
  hasAllergens: string;
  seen: string;
  done: string;

  // Empty state
  queueClear: string;
  lastOrderServed: string;
  ordersServed: string;
  avgTicketTime: string;
  fastestTicket: string;

  // History
  today: string;
  yesterday: string;
  last7Days: string;
  searchPlaceholder: string;
  noOrdersServed: string;
  recalled: string;

  // Settings
  display: string;
  orders: string;
  hardware: string;
  account: string;
  displayMode: string;
  cardsPerRow: string;
  textSize: string;
  statusColours: string;
  customiseStatusColours: string;
  theme: string;
  light: string;
  dark: string;
  compact: string;
  standard: string;
  large: string;
  categoryFilter: string;
  manageCategories: string;
  revenueCenterFilter: string;
  manageStationFilters: string;
  staggerMode: string;
  configureRelease: string;
  servableModifiers: string;
  showAllergenBadges: string;
  sortDefault: string;
  byTime: string;
  byTable: string;
  byType: string;
  mainPrintingDevice: string;
  soundSettings: string;
  volumeAndAlerts: string;
  connection: string;
  wsAndSync: string;
  deviceName: string;
  language: string;
  devMode: string;
  showFlowSelector: string;
  logOut: string;
  logOutConfirm: string;
  logOutDescription: string;
  cancel: string;
  saveChanges: string;

  // Language modal
  languageRegion: string;
  languageScope: string;
  appInterface: string;
  menuItems: string;
  both: string;
  searchLanguages: string;
  moreLanguages: string;
  regionalFormat: string;
  dateFormat: string;
  timeFormat: string;
}

const translations: Record<LanguageCode, Translations> = {
  'en-US': {
    ordersInQueue: 'Orders in Queue',
    sort: 'Sort',
    sortByTime: 'By Time',
    sortByTable: 'By Table',
    sortByType: 'By Type',
    grid: 'Grid',
    horizontal: 'Horizontal',
    stagger: 'Stagger',
    menu: 'Menu',
    home: 'Home',
    history: 'History',
    alerts: 'Alerts',
    settings: 'Settings',
    newOrders: 'New Orders',
    inProgress: 'In Progress',
    hideCompleted: 'Hide Completed',
    switchToPOS: 'Switch to POS',
    products: 'products',
    hasAllergens: 'has allergens',
    seen: 'SEEN',
    done: 'DONE',
    queueClear: 'Queue is clear, great work!',
    lastOrderServed: 'Last order served at 2:34 PM - 48 orders completed today',
    ordersServed: 'Orders Served',
    avgTicketTime: 'Avg Ticket Time',
    fastestTicket: 'Fastest Ticket',
    today: 'Today',
    yesterday: 'Yesterday',
    last7Days: 'Last 7 Days',
    searchPlaceholder: 'Search order, table, server...',
    noOrdersServed: 'No orders served yet today',
    recalled: 'recalled and added to queue',
    display: 'DISPLAY',
    orders: 'ORDERS',
    hardware: 'HARDWARE',
    account: 'ACCOUNT',
    displayMode: 'Display Mode',
    cardsPerRow: 'Cards Per Row',
    textSize: 'Text Size',
    statusColours: 'Status Colours',
    customiseStatusColours: 'Customise order status colours',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    compact: 'Compact',
    standard: 'Standard',
    large: 'Large',
    categoryFilter: 'Category Filter',
    manageCategories: 'Manage active categories',
    revenueCenterFilter: 'Revenue Center Filter',
    manageStationFilters: 'Manage station filters',
    staggerMode: 'Stagger Mode',
    configureRelease: 'Configure release schedule',
    servableModifiers: 'Servable Modifiers',
    showAllergenBadges: 'Show Allergen Badges',
    sortDefault: 'Sort Default',
    byTime: 'By Time',
    byTable: 'By Table',
    byType: 'By Type',
    mainPrintingDevice: 'Main Printing Device',
    soundSettings: 'Sound Settings',
    volumeAndAlerts: 'Volume and alert sounds',
    connection: 'Connection',
    wsAndSync: 'WebSocket and sync settings',
    deviceName: 'Device Name',
    language: 'Language',
    devMode: 'Dev Mode',
    showFlowSelector: 'Show flow selector on login',
    logOut: 'LOG OUT',
    logOutConfirm: 'Log Out?',
    logOutDescription: 'You will be returned to the sign-in screen. Any unsaved settings will be lost.',
    cancel: 'Cancel',
    saveChanges: 'Save Changes',
    languageRegion: 'Language & Region',
    languageScope: 'Language Scope',
    appInterface: 'App Interface',
    menuItems: 'Menu Items',
    both: 'Both',
    searchLanguages: 'Search languages...',
    moreLanguages: 'More languages coming soon',
    regionalFormat: 'Regional Format',
    dateFormat: 'Date Format',
    timeFormat: 'Time Format',
  },
  'en-GB': {
    ordersInQueue: 'Orders in Queue',
    sort: 'Sort',
    sortByTime: 'By Time',
    sortByTable: 'By Table',
    sortByType: 'By Type',
    grid: 'Grid',
    horizontal: 'Horizontal',
    stagger: 'Stagger',
    menu: 'Menu',
    home: 'Home',
    history: 'History',
    alerts: 'Alerts',
    settings: 'Settings',
    newOrders: 'New Orders',
    inProgress: 'In Progress',
    hideCompleted: 'Hide Completed',
    switchToPOS: 'Switch to POS',
    products: 'products',
    hasAllergens: 'has allergens',
    seen: 'SEEN',
    done: 'DONE',
    queueClear: 'Queue is clear, great work!',
    lastOrderServed: 'Last order served at 2:34 PM - 48 orders completed today',
    ordersServed: 'Orders Served',
    avgTicketTime: 'Avg Ticket Time',
    fastestTicket: 'Fastest Ticket',
    today: 'Today',
    yesterday: 'Yesterday',
    last7Days: 'Last 7 Days',
    searchPlaceholder: 'Search order, table, server...',
    noOrdersServed: 'No orders served yet today',
    recalled: 'recalled and added to queue',
    display: 'DISPLAY',
    orders: 'ORDERS',
    hardware: 'HARDWARE',
    account: 'ACCOUNT',
    displayMode: 'Display Mode',
    cardsPerRow: 'Cards Per Row',
    textSize: 'Text Size',
    statusColours: 'Status Colours',
    customiseStatusColours: 'Customise order status colours',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    compact: 'Compact',
    standard: 'Standard',
    large: 'Large',
    categoryFilter: 'Category Filter',
    manageCategories: 'Manage active categories',
    revenueCenterFilter: 'Revenue Centre Filter',
    manageStationFilters: 'Manage station filters',
    staggerMode: 'Stagger Mode',
    configureRelease: 'Configure release schedule',
    servableModifiers: 'Servable Modifiers',
    showAllergenBadges: 'Show Allergen Badges',
    sortDefault: 'Sort Default',
    byTime: 'By Time',
    byTable: 'By Table',
    byType: 'By Type',
    mainPrintingDevice: 'Main Printing Device',
    soundSettings: 'Sound Settings',
    volumeAndAlerts: 'Volume and alert sounds',
    connection: 'Connection',
    wsAndSync: 'WebSocket and sync settings',
    deviceName: 'Device Name',
    language: 'Language',
    devMode: 'Dev Mode',
    showFlowSelector: 'Show flow selector on login',
    logOut: 'LOG OUT',
    logOutConfirm: 'Log Out?',
    logOutDescription: 'You will be returned to the sign-in screen. Any unsaved settings will be lost.',
    cancel: 'Cancel',
    saveChanges: 'Save Changes',
    languageRegion: 'Language & Region',
    languageScope: 'Language Scope',
    appInterface: 'App Interface',
    menuItems: 'Menu Items',
    both: 'Both',
    searchLanguages: 'Search languages...',
    moreLanguages: 'More languages coming soon',
    regionalFormat: 'Regional Format',
    dateFormat: 'Date Format',
    timeFormat: 'Time Format',
  },
  ar: {
    ordersInQueue: 'الطلبات في الانتظار',
    sort: 'ترتيب',
    sortByTime: 'حسب الوقت',
    sortByTable: 'حسب الطاولة',
    sortByType: 'حسب النوع',
    grid: 'شبكة',
    horizontal: 'أفقي',
    stagger: 'متدرج',
    menu: 'القائمة',
    home: 'الرئيسية',
    history: 'السجل',
    alerts: 'التنبيهات',
    settings: 'الإعدادات',
    newOrders: 'طلبات جديدة',
    inProgress: 'قيد التحضير',
    hideCompleted: 'إخفاء المكتملة',
    switchToPOS: 'التبديل إلى POS',
    products: 'منتجات',
    hasAllergens: 'يحتوي على مسببات حساسية',
    seen: 'تم الاطلاع',
    done: 'تم',
    queueClear: 'قائمة الانتظار فارغة، عمل رائع!',
    lastOrderServed: 'آخر طلب تم تقديمه الساعة 2:34 م - 48 طلب مكتمل اليوم',
    ordersServed: 'الطلبات المقدمة',
    avgTicketTime: 'متوسط وقت الطلب',
    fastestTicket: 'أسرع طلب',
    today: 'اليوم',
    yesterday: 'أمس',
    last7Days: 'آخر 7 أيام',
    searchPlaceholder: 'بحث عن طلب، طاولة، نادل...',
    noOrdersServed: 'لم يتم تقديم أي طلبات اليوم',
    recalled: 'تم استرجاعه وإضافته للقائمة',
    display: 'العرض',
    orders: 'الطلبات',
    hardware: 'الأجهزة',
    account: 'الحساب',
    displayMode: 'وضع العرض',
    cardsPerRow: 'بطاقات في الصف',
    textSize: 'حجم الخط',
    statusColours: 'ألوان الحالة',
    customiseStatusColours: 'تخصيص ألوان حالة الطلب',
    theme: 'المظهر',
    light: 'فاتح',
    dark: 'داكن',
    compact: 'مضغوط',
    standard: 'قياسي',
    large: 'كبير',
    categoryFilter: 'تصفية الفئات',
    manageCategories: 'إدارة الفئات النشطة',
    revenueCenterFilter: 'تصفية مركز الإيرادات',
    manageStationFilters: 'إدارة فلاتر المحطة',
    staggerMode: 'الوضع المتدرج',
    configureRelease: 'تهيئة جدول الإصدار',
    servableModifiers: 'الإضافات القابلة للتقديم',
    showAllergenBadges: 'إظهار شارات الحساسية',
    sortDefault: 'الترتيب الافتراضي',
    byTime: 'حسب الوقت',
    byTable: 'حسب الطاولة',
    byType: 'حسب النوع',
    mainPrintingDevice: 'جهاز الطباعة الرئيسي',
    soundSettings: 'إعدادات الصوت',
    volumeAndAlerts: 'مستوى الصوت والتنبيهات',
    connection: 'الاتصال',
    wsAndSync: 'إعدادات WebSocket والمزامنة',
    deviceName: 'اسم الجهاز',
    language: 'اللغة',
    devMode: 'وضع المطور',
    showFlowSelector: 'إظهار محدد التدفق عند تسجيل الدخول',
    logOut: 'تسجيل الخروج',
    logOutConfirm: 'تسجيل الخروج؟',
    logOutDescription: 'ستعود إلى شاشة تسجيل الدخول. ستفقد الإعدادات غير المحفوظة.',
    cancel: 'إلغاء',
    saveChanges: 'حفظ التغييرات',
    languageRegion: 'اللغة والمنطقة',
    languageScope: 'نطاق اللغة',
    appInterface: 'واجهة التطبيق',
    menuItems: 'عناصر القائمة',
    both: 'كلاهما',
    searchLanguages: 'البحث عن لغات...',
    moreLanguages: 'المزيد من اللغات قريبا',
    regionalFormat: 'التنسيق الإقليمي',
    dateFormat: 'تنسيق التاريخ',
    timeFormat: 'تنسيق الوقت',
  },
  es: {
    ordersInQueue: 'Pedidos en cola',
    sort: 'Ordenar',
    sortByTime: 'Por tiempo',
    sortByTable: 'Por mesa',
    sortByType: 'Por tipo',
    grid: 'Cuadricula',
    horizontal: 'Horizontal',
    stagger: 'Escalonado',
    menu: 'Menu',
    home: 'Inicio',
    history: 'Historial',
    alerts: 'Alertas',
    settings: 'Ajustes',
    newOrders: 'Nuevos pedidos',
    inProgress: 'En progreso',
    hideCompleted: 'Ocultar completados',
    switchToPOS: 'Cambiar a POS',
    products: 'productos',
    hasAllergens: 'tiene alergenos',
    seen: 'VISTO',
    done: 'LISTO',
    queueClear: 'Cola vacia, buen trabajo!',
    lastOrderServed: 'Ultimo pedido servido a las 2:34 PM - 48 pedidos completados hoy',
    ordersServed: 'Pedidos servidos',
    avgTicketTime: 'Tiempo promedio',
    fastestTicket: 'Mas rapido',
    today: 'Hoy',
    yesterday: 'Ayer',
    last7Days: 'Ultimos 7 dias',
    searchPlaceholder: 'Buscar pedido, mesa, mesero...',
    noOrdersServed: 'Sin pedidos servidos hoy',
    recalled: 'recuperado y agregado a la cola',
    display: 'PANTALLA',
    orders: 'PEDIDOS',
    hardware: 'HARDWARE',
    account: 'CUENTA',
    displayMode: 'Modo de pantalla',
    cardsPerRow: 'Tarjetas por fila',
    textSize: 'Tamano de texto',
    statusColours: 'Colores de estado',
    customiseStatusColours: 'Personalizar colores de estado',
    theme: 'Tema',
    light: 'Claro',
    dark: 'Oscuro',
    compact: 'Compacto',
    standard: 'Estandar',
    large: 'Grande',
    categoryFilter: 'Filtro de categoria',
    manageCategories: 'Gestionar categorias activas',
    revenueCenterFilter: 'Filtro de centro de ingresos',
    manageStationFilters: 'Gestionar filtros de estacion',
    staggerMode: 'Modo escalonado',
    configureRelease: 'Configurar calendario de lanzamiento',
    servableModifiers: 'Modificadores servibles',
    showAllergenBadges: 'Mostrar insignias de alergenos',
    sortDefault: 'Orden predeterminado',
    byTime: 'Por tiempo',
    byTable: 'Por mesa',
    byType: 'Por tipo',
    mainPrintingDevice: 'Impresora principal',
    soundSettings: 'Ajustes de sonido',
    volumeAndAlerts: 'Volumen y alertas de sonido',
    connection: 'Conexion',
    wsAndSync: 'Configuracion de WebSocket y sincronizacion',
    deviceName: 'Nombre del dispositivo',
    language: 'Idioma',
    devMode: 'Modo desarrollo',
    showFlowSelector: 'Mostrar selector de flujo al iniciar',
    logOut: 'CERRAR SESION',
    logOutConfirm: 'Cerrar sesion?',
    logOutDescription: 'Volvera a la pantalla de inicio de sesion. Los ajustes no guardados se perderan.',
    cancel: 'Cancelar',
    saveChanges: 'Guardar cambios',
    languageRegion: 'Idioma y region',
    languageScope: 'Alcance del idioma',
    appInterface: 'Interfaz de la app',
    menuItems: 'Elementos del menu',
    both: 'Ambos',
    searchLanguages: 'Buscar idiomas...',
    moreLanguages: 'Mas idiomas proximamente',
    regionalFormat: 'Formato regional',
    dateFormat: 'Formato de fecha',
    timeFormat: 'Formato de hora',
  },
  zh: {
    ordersInQueue: '排队订单',
    sort: '排序',
    sortByTime: '按时间',
    sortByTable: '按桌号',
    sortByType: '按类型',
    grid: '网格',
    horizontal: '水平',
    stagger: '交错',
    menu: '菜单',
    home: '首页',
    history: '历史',
    alerts: '提醒',
    settings: '设置',
    newOrders: '新订单',
    inProgress: '进行中',
    hideCompleted: '隐藏已完成',
    switchToPOS: '切换到POS',
    products: '产品',
    hasAllergens: '含过敏原',
    seen: '已查看',
    done: '完成',
    queueClear: '队列已清空，干得好！',
    lastOrderServed: '最后一单于下午2:34送出 - 今天已完成48单',
    ordersServed: '已送出订单',
    avgTicketTime: '平均出餐时间',
    fastestTicket: '最快出餐',
    today: '今天',
    yesterday: '昨天',
    last7Days: '最近7天',
    searchPlaceholder: '搜索订单、桌号、服务员...',
    noOrdersServed: '今天还没有送出订单',
    recalled: '已召回并加入队列',
    display: '显示',
    orders: '订单',
    hardware: '硬件',
    account: '账户',
    displayMode: '显示模式',
    cardsPerRow: '每行卡片数',
    textSize: '文字大小',
    statusColours: '状态颜色',
    customiseStatusColours: '自定义订单状态颜色',
    theme: '主题',
    light: '浅色',
    dark: '深色',
    compact: '紧凑',
    standard: '标准',
    large: '大号',
    categoryFilter: '类别筛选',
    manageCategories: '管理活跃类别',
    revenueCenterFilter: '营收中心筛选',
    manageStationFilters: '管理站点筛选',
    staggerMode: '交错模式',
    configureRelease: '配置发布计划',
    servableModifiers: '可服务修改',
    showAllergenBadges: '显示过敏原标签',
    sortDefault: '默认排序',
    byTime: '按时间',
    byTable: '按桌号',
    byType: '按类型',
    mainPrintingDevice: '主打印设备',
    soundSettings: '声音设置',
    volumeAndAlerts: '音量和提醒声音',
    connection: '连接',
    wsAndSync: 'WebSocket和同步设置',
    deviceName: '设备名称',
    language: '语言',
    devMode: '开发模式',
    showFlowSelector: '登录时显示流程选择器',
    logOut: '退出登录',
    logOutConfirm: '退出登录？',
    logOutDescription: '您将返回登录界面。未保存的设置将丢失。',
    cancel: '取消',
    saveChanges: '保存更改',
    languageRegion: '语言和地区',
    languageScope: '语言范围',
    appInterface: '应用界面',
    menuItems: '菜单项目',
    both: '全部',
    searchLanguages: '搜索语言...',
    moreLanguages: '更多语言即将推出',
    regionalFormat: '地区格式',
    dateFormat: '日期格式',
    timeFormat: '时间格式',
  },
  vi: {
    ordersInQueue: 'Don hang trong hang doi',
    sort: 'Sap xep',
    sortByTime: 'Theo thoi gian',
    sortByTable: 'Theo ban',
    sortByType: 'Theo loai',
    grid: 'Luoi',
    horizontal: 'Ngang',
    stagger: 'So le',
    menu: 'Menu',
    home: 'Trang chu',
    history: 'Lich su',
    alerts: 'Thong bao',
    settings: 'Cai dat',
    newOrders: 'Don moi',
    inProgress: 'Dang lam',
    hideCompleted: 'An da hoan thanh',
    switchToPOS: 'Chuyen sang POS',
    products: 'san pham',
    hasAllergens: 'co di ung',
    seen: 'DA XEM',
    done: 'XONG',
    queueClear: 'Hang doi trong, lam tot lam!',
    lastOrderServed: 'Don cuoi phuc vu luc 2:34 PM - 48 don hoan thanh hom nay',
    ordersServed: 'Don da phuc vu',
    avgTicketTime: 'Thoi gian TB',
    fastestTicket: 'Nhanh nhat',
    today: 'Hom nay',
    yesterday: 'Hom qua',
    last7Days: '7 ngay qua',
    searchPlaceholder: 'Tim don, ban, nhan vien...',
    noOrdersServed: 'Chua co don nao duoc phuc vu hom nay',
    recalled: 'da thu hoi va them vao hang doi',
    display: 'HIEN THI',
    orders: 'DON HANG',
    hardware: 'PHAN CUNG',
    account: 'TAI KHOAN',
    displayMode: 'Che do hien thi',
    cardsPerRow: 'The moi hang',
    textSize: 'Co chu',
    statusColours: 'Mau trang thai',
    customiseStatusColours: 'Tuy chinh mau trang thai don hang',
    theme: 'Giao dien',
    light: 'Sang',
    dark: 'Toi',
    compact: 'Gon',
    standard: 'Tieu chuan',
    large: 'Lon',
    categoryFilter: 'Loc danh muc',
    manageCategories: 'Quan ly danh muc hoat dong',
    revenueCenterFilter: 'Loc trung tam doanh thu',
    manageStationFilters: 'Quan ly bo loc tram',
    staggerMode: 'Che do so le',
    configureRelease: 'Cau hinh lich phat hanh',
    servableModifiers: 'Tuy chinh phuc vu',
    showAllergenBadges: 'Hien thi huy hieu di ung',
    sortDefault: 'Sap xep mac dinh',
    byTime: 'Theo thoi gian',
    byTable: 'Theo ban',
    byType: 'Theo loai',
    mainPrintingDevice: 'May in chinh',
    soundSettings: 'Cai dat am thanh',
    volumeAndAlerts: 'Am luong va am thanh canh bao',
    connection: 'Ket noi',
    wsAndSync: 'Cai dat WebSocket va dong bo',
    deviceName: 'Ten thiet bi',
    language: 'Ngon ngu',
    devMode: 'Che do nha phat trien',
    showFlowSelector: 'Hien thi chon luong khi dang nhap',
    logOut: 'DANG XUAT',
    logOutConfirm: 'Dang xuat?',
    logOutDescription: 'Ban se tro ve man hinh dang nhap. Cac cai dat chua luu se bi mat.',
    cancel: 'Huy',
    saveChanges: 'Luu thay doi',
    languageRegion: 'Ngon ngu & Khu vuc',
    languageScope: 'Pham vi ngon ngu',
    appInterface: 'Giao dien ung dung',
    menuItems: 'Muc menu',
    both: 'Ca hai',
    searchLanguages: 'Tim ngon ngu...',
    moreLanguages: 'Them ngon ngu sap ra mat',
    regionalFormat: 'Dinh dang khu vuc',
    dateFormat: 'Dinh dang ngay',
    timeFormat: 'Dinh dang gio',
  },
};

const productNames: Record<LanguageCode, Record<string, string>> = {
  'en-US': {},
  'en-GB': {},
  ar: {},
  es: {
    'Cheese Selection': 'Selección de Quesos',
    'Meatballs': 'Albóndigas',
    'Filet Mignon': 'Filete Mignon',
    'Tres Leches': 'Tres Leches',
    'Grilled Salmon': 'Salmón a la Parrilla',
    'Caesar Salad': 'Ensalada César',
    'Spring Rolls': 'Rollitos de Primavera',
    'Pad Thai': 'Pad Thai',
    'Green Curry': 'Curry Verde',
    'Wagyu Steak': 'Bistec Wagyu',
    'Lobster Tail': 'Cola de Langosta',
    'Bruschetta Platter': 'Plato de Bruschetta',
    'Chicken Parmigiana': 'Pollo a la Parmesana',
    'Vegetable Risotto': 'Risotto de Verduras',
    'Tiramisu': 'Tiramisú',
    'Fish and Chips': 'Pescado con Papas',
    'Onion Rings': 'Aros de Cebolla',
    'Club Sandwich': 'Sandwich Club',
    'Soup of the Day': 'Sopa del Día',
    'Garlic Bread': 'Pan de Ajo',
    'Lamb Chops': 'Chuletas de Cordero',
    'Mushroom Pasta': 'Pasta de Champiñones',
    'Creme Brulee': 'Crème Brûlée',
    'Margherita Pizza': 'Pizza Margherita',
    'Garlic Knots': 'Nudos de Ajo',
    'Calamari': 'Calamares',
    'Caprese Salad': 'Ensalada Caprese',
    'Ribeye Steak': 'Bistec Ribeye',
    'Sea Bass': 'Lubina',
    'Chicken Caesar Wrap': 'Wrap César de Pollo',
    'Chocolate Lava Cake': 'Volcán de Chocolate',
    'Beef Burger': 'Hamburguesa de Res',
    'Fries': 'Papas Fritas',
    'Garden Salad': 'Ensalada del Jardín',
    'Roasted Chicken': 'Pollo Asado',
    'Grilled Swordfish': 'Pez Espada a la Parrilla',
    'Eggplant Parmesan': 'Berenjena a la Parmesana',
    'Panna Cotta': 'Panna Cotta',
  },
  zh: {
    'Cheese Selection': '芝士拼盘',
    'Meatballs': '肉丸',
    'Filet Mignon': '菲力牛排',
    'Tres Leches': '三奶蛋糕',
    'Grilled Salmon': '烤三文鱼',
    'Caesar Salad': '凯撒沙拉',
    'Spring Rolls': '春卷',
    'Pad Thai': '泰式炒河粉',
    'Green Curry': '绿咖喱',
    'Wagyu Steak': '和牛牛排',
    'Lobster Tail': '龙虾尾',
    'Bruschetta Platter': '意式烤面包拼盘',
    'Chicken Parmigiana': '帕尔马鸡排',
    'Vegetable Risotto': '蔬菜烩饭',
    'Tiramisu': '提拉米苏',
    'Fish and Chips': '炸鱼薯条',
    'Onion Rings': '洋葱圈',
    'Club Sandwich': '总汇三明治',
    'Soup of the Day': '每日例汤',
    'Garlic Bread': '蒜蓉面包',
    'Lamb Chops': '羊排',
    'Mushroom Pasta': '蘑菇意面',
    'Creme Brulee': '焦糖布丁',
    'Margherita Pizza': '玛格丽特披萨',
    'Garlic Knots': '蒜蓉面包结',
    'Calamari': '炸鱿鱼',
    'Caprese Salad': '卡普雷塞沙拉',
    'Ribeye Steak': '肋眼牛排',
    'Sea Bass': '海鲈鱼',
    'Chicken Caesar Wrap': '凯撒鸡肉卷',
    'Chocolate Lava Cake': '熔岩巧克力蛋糕',
    'Beef Burger': '牛肉汉堡',
    'Fries': '薯条',
    'Garden Salad': '田园沙拉',
    'Roasted Chicken': '烤鸡',
    'Grilled Swordfish': '烤旗鱼',
    'Eggplant Parmesan': '帕尔马茄子',
    'Panna Cotta': '奶冻',
  },
  vi: {
    'Cheese Selection': 'Phô Mai Tổng Hợp',
    'Meatballs': 'Thịt Viên',
    'Filet Mignon': 'Thăn Nội Bò',
    'Tres Leches': 'Bánh Tres Leches',
    'Grilled Salmon': 'Cá Hồi Nướng',
    'Caesar Salad': 'Salad Caesar',
    'Spring Rolls': 'Chả Giò',
    'Pad Thai': 'Pad Thái',
    'Green Curry': 'Cà Ri Xanh',
    'Wagyu Steak': 'Bò Wagyu',
    'Lobster Tail': 'Đuôi Tôm Hùm',
    'Bruschetta Platter': 'Đĩa Bruschetta',
    'Chicken Parmigiana': 'Gà Parmesan',
    'Vegetable Risotto': 'Cơm Risotto Rau Củ',
    'Tiramisu': 'Tiramisu',
    'Fish and Chips': 'Cá Chiên Khoai Tây',
    'Onion Rings': 'Hành Tây Chiên',
    'Club Sandwich': 'Bánh Mì Club',
    'Soup of the Day': 'Súp Trong Ngày',
    'Garlic Bread': 'Bánh Mì Tỏi',
    'Lamb Chops': 'Sườn Cừu',
    'Mushroom Pasta': 'Mì Nấm',
    'Creme Brulee': 'Crème Brûlée',
    'Margherita Pizza': 'Pizza Margherita',
    'Garlic Knots': 'Bánh Mì Tỏi Xoắn',
    'Calamari': 'Mực Chiên',
    'Caprese Salad': 'Salad Caprese',
    'Ribeye Steak': 'Bò Ribeye',
    'Sea Bass': 'Cá Vược',
    'Chicken Caesar Wrap': 'Cuốn Gà Caesar',
    'Chocolate Lava Cake': 'Bánh Chocolate Nóng Chảy',
    'Beef Burger': 'Burger Bò',
    'Fries': 'Khoai Tây Chiên',
    'Garden Salad': 'Salad Vườn',
    'Roasted Chicken': 'Gà Quay',
    'Grilled Swordfish': 'Cá Kiếm Nướng',
    'Eggplant Parmesan': 'Cà Tím Parmesan',
    'Panna Cotta': 'Panna Cotta',
  },
};

const modifierTexts: Record<LanguageCode, Record<string, string>> = {
  'en-US': {},
  'en-GB': {},
  ar: {},
  es: {
    'Medium Rare': 'Medio crudo',
    'Medium Well': 'Tres cuartos',
    'Medium': 'Medio',
    'Rare': 'Poco hecho',
    'Well Done': 'Bien cocido',
    'Mild': 'Suave',
    'Spicy': 'Picante',
    'Seasoned': 'Sazonado',
    'Pan Seared': 'Sellado en sartén',
    'Potato Wedge': 'Gajos de papa',
    'Mushy Peas': 'Puré de guisantes',
    'Gluten Free Pasta': 'Pasta sin gluten',
    'Dressing on Side': 'Aderezo aparte',
    'Dressing on side': 'Aderezo aparte',
    'Extra Dipping Sauce': 'Salsa extra para mojar',
    'Berry Coulis': 'Coulis de frutos rojos',
    'Rosemary Jus': 'Jugo de romero',
    '+ Extra Cheese': '+ Queso extra',
    '+ Extra Olive Oil': '+ Aceite de oliva extra',
    '+ Extra Croutons': '+ Crutones extra',
    '+ Extra Shrimp': '+ Camarones extra',
    '+ Extra Sauce': '+ Salsa extra',
    '+ Extra Garlic Butter': '+ Mantequilla de ajo extra',
    '+ Extra Mozzarella': '+ Mozzarella extra',
    '+ Truffle Butter': '+ Mantequilla de trufa',
    '+ Garlic Butter': '+ Mantequilla de ajo',
    '+ Lemon Sauce': '+ Salsa de limón',
    '+ Avocado': '+ Aguacate',
    '+ Bacon': '+ Tocino',
    '+ Berry Coulis': '+ Coulis de frutos rojos',
    '+ Marinara': '+ Marinara',
    '+ Mint Sauce': '+ Salsa de menta',
    '+ Peppercorn Sauce': '+ Salsa de pimienta',
    '+ Rosemary Jus': '+ Jugo de romero',
    '+ Vanilla Ice Cream': '+ Helado de vainilla',
    'No Asparagus': 'Sin espárragos',
    'No Butter': 'Sin mantequilla',
    'No Capers': 'Sin alcaparras',
    'No Mayo': 'Sin mayonesa',
    'No Parmesan': 'Sin parmesano',
    'No Pickles': 'Sin pepinillos',
  },
  zh: {
    'Medium Rare': '三分熟',
    'Medium Well': '七分熟',
    'Medium': '五分熟',
    'Rare': '一分熟',
    'Well Done': '全熟',
    'Mild': '微辣',
    'Spicy': '辣',
    'Seasoned': '调味',
    'Pan Seared': '煎制',
    'Potato Wedge': '土豆角',
    'Mushy Peas': '豌豆泥',
    'Gluten Free Pasta': '无麸质意面',
    'Dressing on Side': '酱汁另放',
    'Dressing on side': '酱汁另放',
    'Extra Dipping Sauce': '额外蘸酱',
    'Berry Coulis': '莓果酱',
    'Rosemary Jus': '迷迭香汁',
    '+ Extra Cheese': '+ 加芝士',
    '+ Extra Olive Oil': '+ 加橄榄油',
    '+ Extra Croutons': '+ 加面包丁',
    '+ Extra Shrimp': '+ 加虾',
    '+ Extra Sauce': '+ 加酱汁',
    '+ Extra Garlic Butter': '+ 加蒜蓉黄油',
    '+ Extra Mozzarella': '+ 加马苏里拉',
    '+ Truffle Butter': '+ 加松露黄油',
    '+ Garlic Butter': '+ 加蒜蓉黄油',
    '+ Lemon Sauce': '+ 加柠檬酱',
    '+ Avocado': '+ 加牛油果',
    '+ Bacon': '+ 加培根',
    '+ Berry Coulis': '+ 加莓果酱',
    '+ Marinara': '+ 加番茄酱',
    '+ Mint Sauce': '+ 加薄荷酱',
    '+ Peppercorn Sauce': '+ 加胡椒酱',
    '+ Rosemary Jus': '+ 加迷迭香汁',
    '+ Vanilla Ice Cream': '+ 加香草冰淇淋',
    'No Asparagus': '不要芦笋',
    'No Butter': '不要黄油',
    'No Capers': '不要刺山柑',
    'No Mayo': '不要蛋黄酱',
    'No Parmesan': '不要帕尔马干酪',
    'No Pickles': '不要泡菜',
  },
  vi: {
    'Medium Rare': 'Tái chín',
    'Medium Well': 'Chín vừa',
    'Medium': 'Vừa',
    'Rare': 'Tái',
    'Well Done': 'Chín kỹ',
    'Mild': 'Ít cay',
    'Spicy': 'Cay',
    'Seasoned': 'Tẩm gia vị',
    'Pan Seared': 'Áp chảo',
    'Potato Wedge': 'Khoai tây cắt múi',
    'Mushy Peas': 'Đậu nghiền',
    'Gluten Free Pasta': 'Mì không gluten',
    'Dressing on Side': 'Nước sốt riêng',
    'Dressing on side': 'Nước sốt riêng',
    'Extra Dipping Sauce': 'Thêm nước chấm',
    'Berry Coulis': 'Sốt berry',
    'Rosemary Jus': 'Nước sốt hương thảo',
    '+ Extra Cheese': '+ Thêm phô mai',
    '+ Extra Olive Oil': '+ Thêm dầu ô liu',
    '+ Extra Croutons': '+ Thêm bánh mì nướng',
    '+ Extra Shrimp': '+ Thêm tôm',
    '+ Extra Sauce': '+ Thêm sốt',
    '+ Extra Garlic Butter': '+ Thêm bơ tỏi',
    '+ Extra Mozzarella': '+ Thêm mozzarella',
    '+ Truffle Butter': '+ Thêm bơ nấm truffle',
    '+ Garlic Butter': '+ Thêm bơ tỏi',
    '+ Lemon Sauce': '+ Thêm sốt chanh',
    '+ Avocado': '+ Thêm bơ',
    '+ Bacon': '+ Thêm thịt xông khói',
    '+ Berry Coulis': '+ Thêm sốt berry',
    '+ Marinara': '+ Thêm sốt marinara',
    '+ Mint Sauce': '+ Thêm sốt bạc hà',
    '+ Peppercorn Sauce': '+ Thêm sốt tiêu',
    '+ Rosemary Jus': '+ Thêm sốt hương thảo',
    '+ Vanilla Ice Cream': '+ Thêm kem vanilla',
    'No Asparagus': 'Không măng tây',
    'No Butter': 'Không bơ',
    'No Capers': 'Không nụ bạch hoa',
    'No Mayo': 'Không mayonnaise',
    'No Parmesan': 'Không phô mai parmesan',
    'No Pickles': 'Không dưa chua',
  },
};

const courseNames: Record<LanguageCode, Record<string, string>> = {
  'en-US': {},
  'en-GB': {},
  ar: {
    'APPETIZER': 'مقبلات',
    'ENTREE': 'طبق رئيسي',
    'DESSERT': 'حلويات',
    'SALAD': 'سلطة',
    'SOUP': 'شوربة',
    'SIDE': 'طبق جانبي',
    'BEVERAGE': 'مشروبات',
    'Salad': 'سلطة',
    'Entree': 'طبق رئيسي',
    'Dessert': 'حلويات',
  },
  es: {
    'APPETIZER': 'ENTRADA',
    'ENTREE': 'PLATO PRINCIPAL',
    'DESSERT': 'POSTRE',
    'SALAD': 'ENSALADA',
    'SOUP': 'SOPA',
    'SIDE': 'ACOMPAÑAMIENTO',
    'BEVERAGE': 'BEBIDA',
    'Salad': 'Ensalada',
    'Entree': 'Plato Principal',
    'Dessert': 'Postre',
  },
  zh: {
    'APPETIZER': '开胃菜',
    'ENTREE': '主菜',
    'DESSERT': '甜点',
    'SALAD': '沙拉',
    'SOUP': '汤',
    'SIDE': '配菜',
    'BEVERAGE': '饮料',
    'Salad': '沙拉',
    'Entree': '主菜',
    'Dessert': '甜点',
  },
  vi: {
    'APPETIZER': 'KHAI VỊ',
    'ENTREE': 'MÓN CHÍNH',
    'DESSERT': 'TRÁNG MIỆNG',
    'SALAD': 'SALAD',
    'SOUP': 'SÚP',
    'SIDE': 'MÓN PHỤ',
    'BEVERAGE': 'THỨC UỐNG',
    'Salad': 'Salad',
    'Entree': 'Món Chính',
    'Dessert': 'Tráng Miệng',
  },
};

const allergenLabels: Record<LanguageCode, Record<string, string>> = {
  'en-US': {},
  es: {
    'PEANUT': 'MANÍ',
    'GLUTEN': 'GLUTEN',
    'DAIRY': 'LÁCTEO',
    'EGG': 'HUEVO',
    'FISH': 'PESCADO',
    'SHELLFISH': 'MARISCO',
    'SOY': 'SOJA',
    'NUT': 'NUEZ',
    'SESAME': 'SÉSAMO',
  },
  zh: {
    'PEANUT': '花生',
    'GLUTEN': '麸质',
    'DAIRY': '乳制品',
    'EGG': '鸡蛋',
    'FISH': '鱼类',
    'SHELLFISH': '贝类',
    'SOY': '大豆',
    'NUT': '坚果',
    'SESAME': '芝麻',
  },
  vi: {
    'PEANUT': 'ĐẬU PHỘNG',
    'GLUTEN': 'GLUTEN',
    'DAIRY': 'SỮA',
    'EGG': 'TRỨNG',
    'FISH': 'CÁ',
    'SHELLFISH': 'HẢI SẢN',
    'SOY': 'ĐẬU NÀNH',
    'NUT': 'HẠT',
    'SESAME': 'MÈ',
  },
};

const orderTypeLabels: Record<LanguageCode, Record<string, string>> = {
  'en-US': {},
  es: {
    'DINE IN': 'COMER AQUÍ',
    'TAKE OUT': 'PARA LLEVAR',
    'DELIVERY': 'ENTREGA',
    'BANQUET': 'BANQUETE',
  },
  zh: {
    'DINE IN': '堂食',
    'TAKE OUT': '外带',
    'DELIVERY': '外卖',
    'BANQUET': '宴会',
  },
  vi: {
    'DINE IN': 'TẠI CHỖ',
    'TAKE OUT': 'MANG ĐI',
    'DELIVERY': 'GIAO HÀNG',
    'BANQUET': 'TIỆC',
  },
};

const languageNames: Record<LanguageCode, string> = {
  'en-US': 'English (US)',
  es: 'Español',
  zh: '中文简体',
  vi: 'Tiếng Việt',
};

const languageFlags: Record<LanguageCode, string> = {
  'en-US': '🇺🇸',
  es: '🇪🇸',
  zh: '🇨🇳',
  vi: '🇻🇳',
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: Translations;
  tp: (name: string) => string;
  tm: (text: string) => string;
  tc: (course: string) => string;
  ta: (label: string) => string;
  to: (label: string) => string;
  languageName: string;
  languageFlag: string;
}

const defaultLanguageContext: LanguageContextType = {
  language: 'es',
  setLanguage: () => {},
  t: translations.es,
  tp: (name: string) => productNames.es[name] || name,
  tm: (text: string) => modifierTexts.es[text] || text,
  tc: (course: string) => courseNames.es[course] || course,
  ta: (label: string) => allergenLabels.es[label] || label,
  to: (label: string) => orderTypeLabels.es[label] || label,
  languageName: languageNames.es,
  languageFlag: languageFlags.es,
};

const LanguageContext = createContext<LanguageContextType>(defaultLanguageContext);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem('posai-language');
    return (saved as LanguageCode) || 'es';
  });

  const setLanguage = useCallback((lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem('posai-language', lang);
  }, []);

  const tp = useCallback((name: string) => {
    return productNames[language]?.[name] || name;
  }, [language]);

  const tm = useCallback((text: string) => {
    return modifierTexts[language]?.[text] || text;
  }, [language]);

  const tc = useCallback((course: string) => {
    return courseNames[language]?.[course] || course;
  }, [language]);

  const ta = useCallback((label: string) => {
    return allergenLabels[language]?.[label] || label;
  }, [language]);

  const to = useCallback((label: string) => {
    return orderTypeLabels[language]?.[label] || label;
  }, [language]);

  const value: LanguageContextType = {
    language,
    setLanguage,
    t: translations[language],
    tp,
    tm,
    tc,
    ta,
    to,
    languageName: languageNames[language],
    languageFlag: languageFlags[language],
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}

